[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install --break-system-packages -r backend/requirements.txt"]

[start]
cmd = "python -m gunicorn --chdir backend --bind 0.0.0.0:$PORT app:app"